---
abstract: 'easy DBI helper (perl inside SQL and blessed results)'
author:
  - 'Dmitry E. Oboukhov <unera@debian.org>'
build_requires:
  DBD::SQLite: 1
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-DR
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 1.4
  Mouse: 0
resources:
  bugtracker: https://github.com/dr-co/dbix-dr/issues
  repository: https://github.com/dr-co/dbix-dr
version: 0.25
