--- #YAML:1.0
name:               DBIx-DR
version:            0.02
abstract:           easy DBI helper (named placeholders and blessed results)
author:
    - Dmitry E. Oboukhov <unera@debian.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    DBD::SQLite:  1
requires:
    DBD::SQLite:  1
    DBI:          1.4
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
