--- #YAML:1.0
name:               DBIx-DR
version:            0.17
abstract:           easy DBI helper (perl inside SQL and blessed results)
author:
    - Dmitry E. Oboukhov <unera@debian.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    DBD::SQLite:  1
requires:
    DBI:    1.4
    Mouse:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
